export default {
  // dev server: 52.221.225.29
  // production server:  18.139.238.80

  BASE_URL: 'http://52.221.225.29/api/',

  ENDPOINTS: {},
  KEYS: {
    KEY: 'key',
    METHOD: 'method',
    RESOURCE: 'resource',
    FILTERS_USERNAME: 'filters[username]',
    FILTERS_PASSWORD: 'filters[password]',
    FILTERS_EMAIL: 'filters[email]',
    FILTERS_PIN: 'filters[pin]',
    FILTERS_ID: 'filters[id]',
    TEMPORARY_TOKEN: 'filters[temporaryToken]',
    FCM_TOKEN: 'filters[fcmtoken]',
    DEVICE_ID: 'filters[deviceId]',
    FILTERS_QRVALUE: 'filters[qrvalue]',
    DATA_STATUS: 'data[status]',
    DATA_ID: 'data[id]',
    DATA_TASK_ID: 'data[taskid]',
    DATA_STAFFID: 'data[staffid]',
    DATA_SCHEDULEID: 'data[scheduleid]',
    DATA_CYCLEID: 'data[cycleid]',
    DATA_DESCRIPTION: 'data[description]',
    DATA_DATE: 'data[date]',
    DATA_START: 'data[start]',
    DATA_END: 'data[end]',
    DATA_HEIGHT: 'data[height]',
    DATA_DIAMETER: 'data[diameter]',
    DATA_HEALTH: 'data[health]',
    DATA_RADIUS: 'data[radius]',
    DATA_TASKID: 'data[taskid]',
    DATA_TASKTYPE: 'data[tasktype]',
    DATA_LAT: 'data[lat]',
    DATA_LNG: 'data[lng]',
    DATA_ASSETID: 'data[assetid]',
    DATA_ADMIN_ID: 'data[adminid]',
    DATA_VITAL_ASSETID: 'data[assetid][]',
    DATA_FILE: 'file[]',
    DATA_DERPARTMENTID: 'data[departmentid]',
    DATA_CLIENTID: 'data[clientid]',
    DATA_USERID: 'data[userid]',
    DATA_PROJECTID: 'data[projectid]',
    DATA_NOTES: 'data[notes]',
    DATA_SUBJECT: 'data[subject]',
    DATA_ASSETTYPE: 'data[assettype]',
    DATA_EMAIL: 'data[email]',
    DATA_TREEID: 'data[treeid]',
    DATA_NOTE: 'data[note]',
    DATA_RECORDED_DATE: 'data[recorded_date]',
    DATA_START_TIME: 'data[starttime]',
    DATA_END_TIME: 'data[endtime]',
    DATA_TREE_VITAL: 'data[treevital]',
    LAST_SYNC_AT: 'last_sync_at',
  },
};
